// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evzrmtziruuaykkaajke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2enJtdHppcnV1YXlra2FhamtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mzc4NjMsImV4cCI6MjA2NzAxMzg2M30.I8ySKM6j3L6mmShSrNx77wYF4YgqN75yLeMWoaYSWpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});